### ISSUE TITLE
Joda DateTime custom mapper in jackson is returning huge timestamps - investigation of impact

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#10]
It is needed to investigate why `jackson-datatype-joda` is transforming `DateTime` to weird timestamp with timezone:

    "product": {
          "name": "JG-BASE",
          "version": "0.4-DEV-SNAPSHOT",
          "validFrom": 1437775200000,
          "validTo": 1469397600000
     }

According to http://www.4webhelp.net/us/timestamp.php e.g.:

*1437775200 translates to Friday, July 24th 2015, 22:00:00 (GMT)*

Why values are multiplied by 1000 and is it bug or not

**Comment by soyerr** [comment]
IMO these value: 1437775200000 is more lightweight than whole date :Friday, July 24th 2015, 22:00:00 (GMT). We must remeber about JSON target. It should be lightweight to send via internet protocol. As you saw it easy to convert to friendly form, Im sure jackson has api for that

**Comment by baart92** [comment]
It is ok, test `org.jgrades.rest.DateTimeMapperTest` passed. Issue can be closed.
