### ISSUE TITLE
H2 DB is blocking undeploy of REST war application

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#11]
There is a problem during undeploy or redeploy REST Web Services war due to incorrect behaviour of H2 JDBC driver:

    09-Aug-2015 23:37:43.275 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [jg-rest] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
    09-Aug-2015 23:37:43.278 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [jg-rest] appears to have started a thread named [MVStore background writer nio:C:/jgrades/internal/licensing.db.mv.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
     java.lang.Object.wait(Native Method)
     org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2578)

In some cases undeploying is impossible and tomcat needs to be shutdown.

**Comment by soyerr** [comment]
It's seems like open transaction with DB.
Are you sure,you closing correctly all connections with DB?

**Comment by baart92** [comment]
the problem occured only in application builded with dev profile. It is connected with `hibernate.hbm2ddl.auto` which is set to `create-drop`, which mean "on teardown application drop entire database". But unfortunatelly, hibernate is trying to drop DB after the connection is closed and JDBC driver unloaded. I will try to affect on order of above actions

**Comment by baart92** [comment]
It turns out that problem is associated with cargo plugin (for un/re/deployment). Cargo is just putting/removing application from tomcat's directory webapp, which cause unexpected unregistering all contexts and jdbc driver. Then, lock for db file is not removed, so next deployment of application failed.

Workaround is to using cargo maven plugin only for deployment application to container which hasn't allready running jg-rest application. For reload and undeployment use features available though Tomcat Web Application Manager.
