### ISSUE TITLE
INFO log records in files for WARN/DEBUG logs

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#12]
In file for WARN logs there are many INFO log records. Similarly in file for DEBUG logs there are also INFO log records. Investigate why this happen

**Comment by soyerr** [comment]
Could you give me line of code where you're trying use logger?

**Comment by soyerr** [comment]
Please check that bug now. 
Probably cause was set only appender for <root level="INFO">. That was changed on ALL level.

**Comment by baart92** [comment]
Fixed with new implementation of logger (#17 PR). Can be closed.
