### ISSUE TITLE
Logger properties setting & services correction

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#13]
Correct processing of properties using solution discussed today

**Comment by soyerr** [comment]
Could you add photo what you made after our miting?

**Comment by baart92** [comment]
https://drive.google.com/file/d/0B8PCqq_AwLMSb2d3OVBlVk9EdTA/view?usp=sharing
https://drive.google.com/file/d/0B8PCqq_AwLMSSEVIMDVsbmNCWlk/view?usp=sharing

**Comment by baart92** [comment]
Fixed with new implementation of logger (#17 PR). Can be closed.
