### ISSUE TITLE
Correction of configuration provided vagrant's VM (+ docs)

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#16]
**I. State of system "out of the box" - results and needed repairing actions**

1. vagrant/vagrant account with sudoers -- OK
* omc/omc account without sudoers -- OK
* root/root account access (setting password) - NOK
  * Solution: as vagrant user you should run `sudo passwd root` and enter `root` password
* ssh access for vagrant account -- OK
* ssh access for omc account -- OK
* ssh access for root account -- NOK
  * Solution: as root user run command `sed -i "s/PermitRootLogin without-password/PermitRootLogin yes/" /etc/ssh/sshd_config`
* directory for jGrades logs: /var/log/jgrades exists -- NOK
* directory for jGrades internal files: /etc/opt/jgrades exists -- NOK
* directory for jGrades local backup: /var/backups/jgrades exists -- NOK
* testbed keystore in /etc/opt/jgrades/jg-ks.jceks exists -- NOK
  * Solution: Copy from repository: `jg-backend/installation/jg-install/src/main/resources/jg-ks.jceks`
* testbed secure data in /etc/opt/jgrades/sec.dat exists -- NOK
  * Solution: Copy from repository: `jg-backend/installation/jg-install/src/main/resources/sec.dat`
* installation of GIT client -- NOK
* installation of Java at least version 1.8.0_45 -- OK (Java 1.8.0_51 installed)
* installation of Apache Maven at least version 3.2.2 -- OK (Apache Maven 3.3.3 installed)
* installation of PostgreSQL at least version 9.3.9 -- OK
* make PostgreSQL to listen on all addresses -- NOK
  * Solution: as root run `sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/9.3/main/postgresql.conf`
* allow all hosts to connect with PostgreSQL -- NOK
  * Solution: as root run *sed -i "s,127.0.0.1/32,0.0.0.0/0,g" /etc/postgresql/9.3/main/pg_hba.conf*
* define password for `postgres` user -- NOK
  * Solution: run as root `sudo -u postgres psql postgres`, then type `\password postgres`, then enter password `postgres`, exit pressing crtl+D and restart service with command `/etc/init.d/postgresql restart`
* configure PostgreSQL port tunneling -- NOK
  * Solution: Add to Vagrantfile line: `config.vm.network "forwarded_port", guest: 5432, host: 5433`. Note that in host the default postgresql port (5432) can be busy after installation pgAdmin III. That's why another port (5433) was chosen
* installation of Apache Tomcat at least version 8.0.22-2 -- OK (Apache Tomcat 8.0.24 installed)
* configure Apache Tomcat port tunneling -- NOK
  * Solution: Add to Vagrantfile line: `config.vm.network "forwarded_port", guest: 8005, host: 8080`. 
* Apache Tomcat directories should be available only for `tomcat8` user-- NOK (directories `/etc/tomcat8`, `/usr/share/tomcat8` are have chmod 700 and belong to `root`)
  * Solution: Run given commands as root: 
    * `sed -i "s/TOMCAT8_USER=root/TOMCAT8_USER=tomcat8/" /etc/default/tomcat8`
    * `sed -i "s/TOMCAT8_USER=root/TOMCAT8_USER=tomcat8/" /etc/init.d/tomcat8`
    * `sudo chown -R tomcat8 /etc/tomcat8`
    * `sudo chmod -R 700 /etc/tomcat8`
    * `sudo chown -R tomcat8 /usr/share/tomcat8`
    * `sudo chmod -R 700 /usr/share/tomcat8`
* welcome Apache Tomcat should be visible in browser -- NOK
  * Connection refused using `wget 127.0.0.1:8005`. I don't know what is a root cost.... You need investigate this issue ASAP

**II. Improve documentation**

1. Write about ssh installation client (suggest GIT installation). Don't forget about write about to add to PATH `C:\Program Files (x86)\Git\bin`)
* Define used ports in VM, and mapping (tunneling) ports to host  - what service (SSH/PSQL/HTTP) on what port
* **VERY IMPORTANT!** describe entire process after first booting VM to having working application (checkout sources, maven installation with production profile, deploying to tomcat using cargo maven plugin, access to swaggerui in browser... maybe I lost something...)
* **QUESTION:** Do you track made changes on original `hashicorp/precise32` VM? You need to describe how to prepare hashicorp/precise32 VM to our purposes step by step... (by step-by-step list or some bash scripts... maybe have a look at install-tools.sh?)
* Describe process of upgrade VM on vagrant servers

**Comment by soyerr** [comment]
//TODO 19 && 21

**Comment by baart92** [comment]
What is a status of issue?

**Comment by soyerr** [comment]
Please check the newest version of vagrant environment and give feedback.

**Comment by baart92** [comment]
How can I upgrade my VM to the newest version?

**Comment by baart92** [comment]
**I. State of system "out of the box" - results and needed repairing actions**

1. vagrant/vagrant account with sudoers -- OK/**OK**
* omc/omc account without sudoers -- OK/**OK**
* ~~root/root account access (setting password)~~ - **root account disabled**
* ssh access for vagrant account -- OK/**OK**
* ssh access for omc account -- OK/**OK**
* ~~ssh access for root account~~ - **root account disabled**
* directory for jGrades logs: /var/log/jgrades exists -- NOK/**OK**
* directory for jGrades internal files: /etc/opt/jgrades exists -- NOK/**OK**
* directory for jGrades local backup: /var/backups/jgrades exists -- NOK/**OK**
* testbed keystore in /etc/opt/jgrades/jg-ks.jceks exists -- NOK/**OK**
* testbed secure data in /etc/opt/jgrades/sec.dat exists -- NOK/**OK**
* installation of GIT client -- NOK/**OK**
* installation of Java at least version 1.8.0_45 -- OK/**OK** (Java 1.8.0_51 installed)
* installation of Apache Maven at least version 3.2.2 -- OK/**OK** (Apache Maven 3.3.3 installed)
* installation of PostgreSQL at least version 9.3.9 -- OK/**OK**
* make PostgreSQL to listen on all addresses -- NOK/**OK**
* allow all hosts to connect with PostgreSQL -- NOK/**OK**
* define password for `postgres` user -- NOK/**OK**
* ~~configure PostgreSQL port tunneling~~ -- **this must be done manually by user by editing `Vagrantfile`**
* installation of Apache Tomcat at least version 8.0.22-2 -- OK/**OK** (Apache Tomcat 8.0.24 installed)
* ~~configure Apache Tomcat port tunneling~~ -- **this must be done manually by user by editing `Vagrantfile`**
* Apache Tomcat directories should be available only for `tomcat8` user-- NOK (directory `/usr/share/tomcat8` have chmod 777)
  * Solution: Run given commands as root: 
    * `sudo chmod -R 700 /usr/share/tomcat8`
* welcome Apache Tomcat should be visible in browser -- NOK/**OK** (running on local 8080 port)

Another checks (steps) will be provided in another issue in nearly future.
