### ISSUE TITLE
Model update: one-to-one rellationship between Student and Parent

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#18]
Due to today arrangements Student entity and Parent entity should be in one-to-one relationship (not many-to-one like now). JPA mappings should be changed.

**Comment by baart92** [comment]
Moreover, we decided today that password field should be moved from User to some Table defined in jg-security module

**Comment by soyerr** [comment]
Could you remind why why 1-1? 
Does we not support situation where parent have 2 child in one school?

**Comment by baart92** [comment]
We agreed that for every student account there will be crated parent account with ".rodz" suffix
