### ISSUE TITLE
Improve documentation of setup local development environment with content about PostgreSQL DB creation

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#19]
Starting jg-rest application needs access to EXISTING PostreSQL database. Describe procedure of installing pgAdmin, setting user password and creating database

**Comment by soyerr** [comment]
Could you explain why?
" jg-rest application needs access to EXISTING PostreSQL database"

**Comment by baart92** [comment]
Because JDBC URL is invalid (noexisting db, incorrect address at all) then spring context is not up so deployment war app is failed

**Comment by baart92** [comment]
After implementation of jg-monitor module deployment of jgrades in failsave. That's mean, invalid or unavailable datasource won't interrupt entire deployment process

**Comment by baart92** [comment]
Documentation updated.
