### ISSUE TITLE
CRITICAL: Logger not working

### ISSUE THREAD

**Issue by baart92** [jgrades/jgrades#5]
I build all project with dev profile with given properties (from main pom.xml):

        <profile>
            <id>dev</id>
            <properties>
                <tomcat.installation.dir>C:/jgrades/tomcat8</tomcat.installation.dir>
                <tomcat.logs.dir>C:/jgrades/tomcat8/logs</tomcat.logs.dir>
                <jg.logs.dir>C:/jgrades/logs</jg.logs.dir>
                <jg.internal.data.dir>C:/jgrades/internal</jg.internal.data.dir>
                <shadow.backup.dir>C:/jgrades/backup</shadow.backup.dir>
                <skip.tests>false</skip.tests>
                <skip.integration.tests>true</skip.integration.tests>
                <db.operations.debug>true</db.operations.debug>
                <db.schema.orm.policy>create-drop</db.schema.orm.policy>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>

1. I created directory **C:\jgrades\logs**
2. Then I deployed **\jg-backend\interface\jg-rest-ws\target\jg-rest.war** on **Apache Tomcat/8.0.24**. 
3. Then I invoked some of REST web service here: **http://localhost:8080/jg-rest/licence/check/product/JG-BASE**
4. Directory **C:\jgrades\logs** is still empty. Why?

Here is **logback_per_module_logging.xml** content taken from **jg-logging-0.4-DEV-SNAPSHOT.jar** from **jg-rest.war/WEB-INF/lib/jg-logging-0.4-DEV-SNAPSHOT.jar**:

    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true">
    <appender name="sift" class="ch.qos.logback.classic.sift.SiftingAppender">
        <discriminator>
            <key>logging_configuration</key>
            <defaultValue>jgrades_log</defaultValue>
        </discriminator>
        <sift>
            <appender class="ch.qos.logback.core.rolling.RollingFileAppender" name="RollingFileAppender-${logging_configuration}">
                <file>C:/jgrades/logs/jgrades_${logging_configuration}_module.log</file>
                <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                    <fileNamePattern>C:/jgrades/logs/jgrades_${logging_configuration}_module_%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                    <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
                        <MaxFileSize>1MB</MaxFileSize>
                    </triggeringPolicy>
                    <triggeringPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                        <MaxBackupIndex>7</MaxBackupIndex>
                    </triggeringPolicy>
                </rollingPolicy>
                <encoder>
                    <charset>UTF-8</charset>
                    <pattern>[%d{yyyy-MM-dd HH:mm:ss}] [%thread] %-5level --> %msg%n</pattern>
                </encoder>
            </appender>
        </sift>
    </appender>

    <logger name="logger">
        <appender-ref ref="sift" />
    </logger>

    </configuration>

Please resolve this ASAP

**Comment by soyerr** [comment]
Hi, 
Do you have logs in other localization or logs arent even created?. 
Please send code when you create and use logger.

**Comment by baart92** [comment]
No, only tomcat logs are created (they are not connected with JGradesLogger I guess).
Example usage:

    public class LicenceCheckService {
        private static final JGradesLogger LOGGER = JGLoggingFactory.getLogger(LicenceCheckService.class);

    ...

    @RequestMapping(value = "/product/{productName}", method = RequestMethod.GET)
    public
    @ResponseBody
    boolean checkForProduct(@PathVariable String productName) {
        LOGGER.info("Checking licence for product {}", productName);
        return licenceCheckingService.checkValidForProduct(productName);
    }
}

**Comment by baart92** [comment]
I guess it is solution:

In default configuration (logback.xml) you should replace:

    <logger name="logger">
        <appender-ref ref="sift" />
    </logger>

by, for example:

    <root level="TRACE">
        <appender-ref ref="sift"/>
    </root>


Is name `logger` used anywhere? Please check this solution and confirm a corectness.

**Comment by soyerr** [comment]
Yes you have absolutely right. 
It will be fixed

**Comment by soyerr** [comment]
Fixed in comit : a3f018e
